#!/bin/bash

DIR=s3/storage-class/one-zone-ia/

echo "Hello Felipe" > $DIR/myfile

aws s3api put-object --body $DIR/myfile --bucket felipedspereira --key myfile --storage-class ONEZONE_IA

rm $DIR/myfile



